apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zodiac
  name: agent-api
  labels:
    app: agent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-api
  template:
    metadata:
      labels:
        app: agent-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: agent
          image: git.tu-berlin.de:5000/zodiac/zodiac-meta/new-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MCP_URL
              value: http://mcp-client-service:8000/chat
          ports:
            - containerPort: 30086
---
apiVersion: v1
kind: Service
metadata:
  namespace: zodiac
  name: agent-api
spec:
  type: ClusterIP
  selector:
    app: agent-api
  ports:
    - protocol: TCP
      port: 30086
      targetPort: 30086
